In [2]:
import numpy as np

In [6]:
# simple array

In [4]:
arr = np.array([10,20,30,40])
print(arr,type(arr))
print(arr,arr.dtype)

[10 20 30 40] <class 'numpy.ndarray'>
[10 20 30 40] int64


In [7]:
# homogeneous array

In [5]:
arr1 = np.array([10,20,30,"AIML"])
print(arr1, arr1.dtype, type(arr1), arr1.shape)

['10' '20' '30' 'AIML'] <U21 <class 'numpy.ndarray'> (4,)


In [ ]:
# multidimensional array

In [8]:
arr2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr2, type(arr2), arr2.dtype, arr2.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'> int64 (3, 3)


In [9]:
# built in array
# prifill
arr3 = np.zeros((2,3), dtype ="int64")
print(arr3, arr3.shape)

[[0 0 0]
 [0 0 0]] (2, 3)


In [11]:
# prefill with ones
arr4 = np.ones((3,))
print(arr4, arr4.shape)

[1. 1. 1.] (3,)


In [12]:
arr4 = np.ones((3,3))
print(arr4, arr4.shape)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] (3, 3)


In [13]:
# prefill with values 
arr5 = np.full((3,4),100)
print(arr5, arr5.shape)

[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)


In [14]:
# identity matrix
arr6 = np.eye(3)
print(arr6, arr6.shape)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)


In [15]:
# using range function
arr7 = np.arange(0,10,1)
print(arr7, arr7.shape)

[0 1 2 3 4 5 6 7 8 9] (10,)


In [16]:
print(np.__version__)

2.4.6
