In [1]:
import numpy as np


In [2]:
arr = np.array([10,20,30,40])
print(arr * 10)

[100 200 300 400]


In [3]:
arr1 = np.array([10,20,30,40])
arr2 = np.array([[101,202,303,404],[10,20,30,40]])
print(arr1 +arr2)



[[111 222 333 444]
 [ 20  40  60  80]]


In [5]:
arr1 = np.array([[10,20,30,40],[10,20,30,40],[23,4,5,7]])
arr2 = np.array([[101,202,303,404],[10,20,30,40]])
print(arr1 +arr2)

ValueError: operands could not be broadcast together with shapes (3,4) (2,4) 