In [1]:
import numpy as np

In [ ]:
# copy array

In [2]:
arr = np.array([10,20,30,40])
copy_arr = arr.copy()
arr[0] = 100

print(arr)
print(copy_arr)

[100  20  30  40]
[10 20 30 40]


In [ ]:
# view array

In [3]:
arr = np.array([10,20,30,40,50])
view_arr = arr.view()
arr[0] = 100

print(arr)
print(view_arr)

[100  20  30  40  50]
[100  20  30  40  50]


In [ ]:
# Make Changes in the VIEW

In [4]:
arr = np.array([10,20,30])
view_arr = arr.view()
view_arr[0] = 200
print(arr)
print(view_arr)

[200  20  30]
[200  20  30]
