In [1]:
import numpy as np


In [2]:
arr = np.array([1, 2, 3, 4, 5])  
print(np.sum(arr))  
print(np.prod(arr)) 
print(np.min(arr))  
# 15 
# 120  
# 1  
print(np.argmin(arr)) # 0 
print(np.max(arr))  
# 5  
print(np.argmax(arr)) # 4  
print(np.mean(arr))  
# 3.0  
print(np.median(arr))  # 3.0  
print(np.std(arr))  
# 1.41  
print(np.var(arr))

15
120
1
0
5
4
3.0
3.0
1.4142135623730951
2.0


In [4]:
# power function
arr = np.array([1, 2, 3, 4, 5])  
print(np.square(arr))  # [1, 4, 9, 16, 25] 
print(np.sqrt(arr))  
# [1, 1.41, 1.73, 2, 2.23]  
print(np.pow(arr, 4))  # [1, 8, 27, 64, 125] 

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1  16  81 256 625]


In [5]:
# log 
print(np.log(arr))  
print(np.log10(arr))  
print(np.log2(arr))  
print(np.exp(arr)) 

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [6]:
# rounding 
print(np.round(2.678)) # 3.0  
print(np.floor(2.678)) # 2.0 
print(np.ceil(2.678))  # 3.0  
print(np.trunc(2.678)) # 2.0

3.0
2.0
3.0
2.0


In [7]:
# Miscellaneous Functions 
arr = np.array([1, 2, -5, 3, 8, -4, 2, 5]) 
print(np.abs(arr))  
print(np.sort(arr))  
# [1 2 5 3 8 4 2 5]  
# [-5 -4 1 2 2 3 5 8] 
print(np.unique(arr))  # [-5 -4 1 2 3 5 8] 

[1 2 5 3 8 4 2 5]
[-5 -4  1  2  2  3  5  8]
[-5 -4  1  2  3  5  8]
