In [1]:
import numpy as np

In [10]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)
print(np.sum(arr2d))

sum_of_column = np.sum(arr2d, axis = 0)
print(sum_of_column)

sum_of_rows = np.sum(arr2d, axis = 1)
print(sum_of_rows)

slicing = arr2d[0:2,1:2]
print(slicing)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [16]:
arr3d = np.array([[[1,2],[2,3],[3,4]],[[4,5],[5,6],[7,8]]])
print(arr3d)

# indexing
print(arr3d[0,1,1])

# slicing for row
slicing_row = arr3d[:,0,:]
print(slicing_row)

# slicing for colomn
slicing_column = arr3d[:,:,0]
print(slicing_column)

[[[1 2]
  [2 3]
  [3 4]]

 [[4 5]
  [5 6]
  [7 8]]]
3
[[1 2]
 [4 5]]
[[1 2 3]
 [4 5 7]]
