In [2]:
import numpy as np

In [3]:
# reshape array
arr = np.array([[1,2,3],[4,5,6]])
print(arr, arr.shape)

reshape = arr.reshape((3,2))
print(reshape, reshape.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)


In [7]:
# flattened array meand 2d array converted into 1d array
flattene_arr = arr.flatten()
print(flattene_arr, flattene_arr.shape)

[1 2 3 4 5 6] (6,)


In [8]:
# indexing

arr1 = np.array([1,2,3,4,5,6])
print(arr1[0])

1


In [15]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2[1][1])

5


In [18]:
# fancy_indexing
arr3 = np.array([1,2,3,4,5,10,7])
idx = [0,1,5]
print(arr3[idx])

[ 1  2 10]


In [22]:
# boolean indexing
arr4 = np.array([10,20,30,40])
print(arr4[arr4 >= 20])

[20 30 40]


In [26]:
# slicing
arr5 = np.array([10,20,30,40,50])
print(arr5[:])
print(arr5[1:])
print(arr5[:5])
print(arr5[::2])

[10 20 30 40 50]
[20 30 40 50]
[10 20 30 40 50]
[10 30 50]
