In [4]:
# vectorization
import numpy as np

arr = np.array([10,20,30,40,50])
print(arr * 5)
print(arr** 2)

arr2 =np.array([10,20,30,404,5])
print(arr + arr2)

[ 50 100 150 200 250]
[ 100  400  900 1600 2500]
[ 20  40  60 444  55]
